# Generated by Django 4.1 on 2023-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0002_about_model_gallery_subscriber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiry',
        ),
    ]
