# Generated by Django 4.1 on 2023-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0004_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='offer_fee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='offer_head',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
