# Generated by Django 4.1 on 2023-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0005_course_details_offer_fee_course_details_offer_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/placement')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('desig', models.CharField(blank=True, max_length=255, null=True)),
                ('plyear', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
