# Generated by Django 4.1 on 2023-05-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0006_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseinternship_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_points', models.TextField(blank=True, default='', null=True)),
                ('course_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eduhub.course_details')),
            ],
        ),
    ]
