# Generated by Django 4.1 on 2023-05-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0008_courojt_details_courseojt_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courseojt_points',
            new_name='courseojtPoints',
        ),
    ]
