# Generated by Django 4.1 on 2023-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0013_remove_course_details_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='ctype',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
