# Generated by Django 4.1 on 2023-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0015_offer_box_delete_courseinternship_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer_box',
        ),
    ]
