# Generated by Django 4.1 on 2023-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0018_offerbox_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbox',
            name='offer_status',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
