# Generated by Django 4.1 on 2023-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0019_alter_offerbox_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_catgeorys',
            name='Fee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='fee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
