# Generated by Django 4.1 on 2023-05-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0020_alter_course_catgeorys_fee_alter_course_details_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='calttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='instalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='placements',
            name='plaalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
