# Generated by Django 4.1 on 2023-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0021_course_details_calttag_instructors_instalttag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='active_status',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
