# Generated by Django 4.1 on 2023-06-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0022_course_details_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='img/gallery')),
                ('img_tag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
