# Generated by Django 4.1 on 2023-06-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0023_gallerys'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='img/event')),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_cond', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, max_length=255, null=True)),
                ('event_time', models.CharField(blank=True, max_length=100, null=True)),
                ('event_loca', models.CharField(blank=True, max_length=100, null=True)),
                ('event_link', models.CharField(blank=True, max_length=100, null=True)),
                ('event_description', models.TextField(blank=True, default='', null=True)),
                ('event_tag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
