# Generated by Django 4.1 on 2023-06-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0024_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
        migrations.DeleteModel(
            name='gallerys',
        ),
    ]
