# Generated by Django 4.1 on 2023-06-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0025_delete_events_delete_gallerys'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='img/event')),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_link', models.CharField(blank=True, max_length=100, null=True)),
                ('event_description', models.TextField(blank=True, default='', null=True)),
                ('event_tag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='img/gallery')),
                ('img_tag', models.TextField(blank=True, default='', null=True)),
                ('event_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eduhub.events')),
            ],
        ),
    ]
