# Generated by Django 4.1 on 2024-01-10 08:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0026_events_gallerys'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('blog_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
