# Generated by Django 4.1 on 2024-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0027_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
